name: "Deploy Documentation"

on: 
  push:
    tags:
      - "*"

jobs:
  docs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3.7

    - name: Conda install dependecies
      shell: bash -l {0}
      run: conda install --yes -c conda-forge pythonocc-core=7.4.0 numpy scipy matplotlib vtk nose setuptools coveralls sphinx sphinx_rtd_theme python=3.7

    - name: Conda info
      shell: bash -l {0}
      run: conda info -a

    - name: Create the new documentation
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "python -m pip install pip sphinx_rtd_theme -U"
        docs-folder: "docs/"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        #deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        publish_dir: ./docs/build/html
        allow_empty_commit: true
